backend/src/main/java/tuneandmanner/wiselydiarybackend/common/config/PGVectorStoreConfig.java
backend/src/main/java/tuneandmanner/wiselydiarybackend/rag/presentation/RAGController.java
backend/src/main/java/tuneandmanner/wiselydiarybackend/rag/service/VectorStoreService.java

VectorDB 저장 로직 수정: StoreType 종류 추가
- Resolves #90 
어떤 변경 사항이 있나요?
-

#90 fix: VectorDB 저장 로직 수정

---

backend/src/main/java/tuneandmanner/wiselydiarybackend/common/config/S3Config.java
backend/src/main/java/tuneandmanner/wiselydiarybackend/common/vectorstore/CustomPgVectorStore.java
backend/src/main/java/tuneandmanner/wiselydiarybackend/imagesubmit/domain/entity/Image.java
backend/src/main/java/tuneandmanner/wiselydiarybackend/imagesubmit/domain/repository/ImageRepository.java
backend/src/main/java/tuneandmanner/wiselydiarybackend/imagesubmit/presentation/ImageController.java
backend/src/main/java/tuneandmanner/wiselydiarybackend/imagesubmit/service/ImageService.java
backend/src/main/java/tuneandmanner/wiselydiarybackend/imagesubmit/service/ImageServiceImpl.java
build.gradle

- 이미지 다중 S3 업로드 이후 DB에 S3 URL 저장 
- deprecated 된 메소드 사용하는 것 수정
- Resolves #48 
어떤 변경 사항이 있나요?
-

#48 이미지 다중 업로드

---

backend/src/main/java/tuneandmanner/wiselydiarybackend/common/exception/ResourceNotFoundException.java
backend/src/main/java/tuneandmanner/wiselydiarybackend/common/exception/S3OperationException.java
backend/src/main/java/tuneandmanner/wiselydiarybackend/imagesubmit/service/ImageServiceImpl.java

이미지 삭제 기능 수정 및 CRD 기능 테스트 완료
- 이미지 삭제 기능 수정 및 
- CRD 기능 테스트 완료
- Resolves #48 
어떤 변경 사항이 있나요?
-

#48 이미지 삭제 기능 수정 및 CRD 기능 테스트 완료

---

backend/src/main/java/tuneandmanner/wiselydiarybackend/diary/presentation/DiaryController.java
backend/src/main/java/tuneandmanner/wiselydiarybackend/diary/service/DiaryService.java

- generate controller, service 메소드 추가
- Resolves #11 
- Resolves #29 
어떤 변경 사항이 있나요?
-

#11, #29 텍스트 일기 생성 기능 개발

---

backend/src/main/java/tuneandmanner/wiselydiarybackend/cartoon/dto/response/InquiryCartoonResponse.java
backend/src/main/java/tuneandmanner/wiselydiarybackend/cartoon/service/CartoonService.java

#97
만화 조회 시 Response 수정
- Resolves #97
어떤 변경 사항이 있나요?
-

#97 만화 조회 시 Response 수정

---

backend/src/main/java/tuneandmanner/wiselydiarybackend/cartoon/dto/response/InquiryCartoonResponse.java
backend/src/main/java/tuneandmanner/wiselydiarybackend/cartoon/service/CartoonService.java
backend/src/main/java/tuneandmanner/wiselydiarybackend/common/exception/type/ExceptionCode.java
backend/src/main/java/tuneandmanner/wiselydiarybackend/diary/domain/repository/DiaryRepository.java
backend/src/main/java/tuneandmanner/wiselydiarybackend/letter/domain/entity/Letter.java
backend/src/main/java/tuneandmanner/wiselydiarybackend/letter/dto/request/CreateLetterRequest.java
backend/src/main/java/tuneandmanner/wiselydiarybackend/letter/dto/response/CreateLetterResponse.java
backend/src/main/java/tuneandmanner/wiselydiarybackend/letter/presentation/LetterController.java
backend/src/main/java/tuneandmanner/wiselydiarybackend/letter/service/LetterService.java

- 일기 요약 코드가 아닌 일기 코드를 참고하도록 수정
- 미반영 만화 관련 코드 추가
- exception code 수정
- Resolves #58 
어떤 변경 사항이 있나요?
- db letter tbl 변경 완료하였습니다.

#58 편지 생성 로직 수정

---

backend/src/main/java/tuneandmanner/wiselydiarybackend/diary/presentation/DiaryController.java
backend/src/main/java/tuneandmanner/wiselydiarybackend/diary/service/DiaryService.java
backend/src/main/java/tuneandmanner/wiselydiarybackend/stt/controller/WhisperController.java

- STT 기능을 통한 일기 생성 기능
- Text를 활용한 일기 생성 기능
- diaryCode 전달
- Resolves #9 
- Resolves #29 
어떤 변경 사항이 있나요?
-

#9, #29 STT를 활용한 일기등록 구현

---

backend/src/main/java/tuneandmanner/wiselydiarybackend/emotion/service/EmotionService.java
backend/src/test/java/tuneandmanner/wiselydiarybackend/emotion/service/EmotionServiceTest.java

- EmotionService 테스트 코드 작성
- Github Actions 의 Test task 통과를 위해
- Resolves #47 
어떤 변경 사항이 있나요?
-

#47 EmotionService 테스트 코드 작성 (for Github Actions)

---

backend/src/main/java/tuneandmanner/wiselydiarybackend/cartoon/presentation/CartoonController.java

#102
만화와 편지 만화 생성 로직 수정
- Resolves #102
어떤 변경 사항이 있나요?
-

#102 만화와 편지 만화 생성 로직 수정

---

backend/src/main/java/tuneandmanner/wiselydiarybackend/letter/domain/repository/LetterRepository.java
backend/src/main/java/tuneandmanner/wiselydiarybackend/letter/presentation/LetterController.java
backend/src/main/java/tuneandmanner/wiselydiarybackend/letter/service/LetterService.java

- 편지 생성 후 재확인 시 재생성되지 않도록 로직 수정
- 조회 및 자동 생성 통합
<장점>
: 단일 API 호출로 처리 가능
: 클라이언트 로직 단순화
: 서버에서 일관된 처리 보장
<단점>
: 항상 201 status를 반환하는 것이 RESTful 설계와 차이가 있을 수 있음
효율성: 단일 API 호출로 조회와 생성을 모두 처리할 수 있어 네트워크 요청을 최소화
단순성: 클라이언트 측 로직이 크게 단순화되어 개발 및 유지보수 용이
일관성: 서버에서 모든 로직을 처리하므로 데이터 일관성을 보장
확장성: 향후 추가적인 비즈니스 로직을 서버 측에 쉽게 통합
사용자 경험: 사용자 입장에서는 항상 빠르고 일관된 응답을 받게 되어 좋은 경험을 제공
현재 상황에서 제일 좋은 선택으로 생각되어 이 방법을 채택했습니다! 다른 의견 있다면 남겨주시면 리팩토링 때 반영하겠습니다.
- Resolves #103 
어떤 변경 사항이 있나요?
- 현재 편지가 2개씩 생성될 때가 있습니다. 다른 분들의 작업을 위해 먼저 PR 올립니다. 현상은 원인 파악 후 바로 수정하겠습니다.

#103 편지 생성 로직 추가 수정 (생성 재확인 시 필요한 로직)

---

backend/src/main/java/tuneandmanner/wiselydiarybackend/diary/domain/repository/DiaryRepository.java
backend/src/main/java/tuneandmanner/wiselydiarybackend/diary/dto/response/DiaryDetailResponse.java
backend/src/main/java/tuneandmanner/wiselydiarybackend/diary/presentation/DiaryController.java
backend/src/main/java/tuneandmanner/wiselydiarybackend/diary/service/DiaryService.java

- 해당 월에 해당하는 일기 전체 조회
- #1 
어떤 변경 사항이 있나요?
-

#1 사용자 일기 조회

---

.github/workflows/deploy.yml

- EC2 세팅 완료
- EC2 배포용 deploy.yml 생성
- Resolves #30 , #49 , #53 
어떤 변경 사항이 있나요?
-

#30 #49 #53 EC2 배포용 deploy.yml 생성

---

.github/workflows/deploy.yml
.github/workflows/gradle.yml
backend/src/main/java/tuneandmanner/wiselydiarybackend/common/config/WebConfig.java

- deploy.yml 수정
- CORS 해결
- Resolves #30 , #49 , #53 
어떤 변경 사항이 있나요?
-

#30 #49 #53 deploy.yml 수정, CORS 해결

---

backend/src/main/java/tuneandmanner/wiselydiarybackend/common/exception/type/ExceptionCode.java
backend/src/main/java/tuneandmanner/wiselydiarybackend/letter/domain/repository/LetterRepository.java
backend/src/main/java/tuneandmanner/wiselydiarybackend/letter/dto/response/InquiryLetterResponse.java
backend/src/main/java/tuneandmanner/wiselydiarybackend/letter/presentation/LetterController.java
backend/src/main/java/tuneandmanner/wiselydiarybackend/letter/service/LetterService.java
backend/src/main/java/tuneandmanner/wiselydiarybackend/music/domain/repository/MusicRepository.java
backend/src/main/java/tuneandmanner/wiselydiarybackend/music/dto/response/InquiryMusicResponse.java
backend/src/main/java/tuneandmanner/wiselydiarybackend/music/dto/response/MusicPlaybackResponse.java
backend/src/main/java/tuneandmanner/wiselydiarybackend/music/presentation/MusicController.java
backend/src/main/java/tuneandmanner/wiselydiarybackend/music/service/MusicService.java

- 해당 날짜, 회원의 생성된 음악 전체 조회 기능
- 해당 날짜, 회원의 생성된 편지 전체 조회 기능
- Resolves #55 #57
어떤 변경 사항이 있나요?
-

#55, #57 음악, 편지 조회 로직 추가 구현

---

.github/workflows/deploy.yml
backend/src/main/java/tuneandmanner/wiselydiarybackend/common/config/WebConfig.java

- setup/github-actions -> dev 코드 병합
어떤 변경 사항이 있나요?
-

setup/github-actions -> dev 코드 통합

---

backend/src/main/java/tuneandmanner/wiselydiarybackend/WiselyDiaryBackendApplication.java

- WiselyDiaryBackendApplication.java 의 EnableConfigurationProperties 수정
어떤 변경 사항이 있나요?
-

fix: EnableConfigurationProperties

---

.github/workflows/deploy.yml
backend/src/main/java/tuneandmanner/wiselydiarybackend/WiselyDiaryBackendApplication.java
backend/src/main/java/tuneandmanner/wiselydiarybackend/cartoon/config/CartoonConfig.java
backend/src/main/java/tuneandmanner/wiselydiarybackend/cartoon/service/CartoonService.java
backend/src/main/java/tuneandmanner/wiselydiarybackend/common/config/SupabaseStorageService.java

- 만화 생성 후 로컬에 저장 안하고 바로 Supabase 에 업로드하도록 변경
- Resolves #78 
어떤 변경 사항이 있나요?
-

fix: 만화 생성 후 로컬에 저장 안하고 바로 Supabase 에 업로드하도록 변경

---

backend/src/main/java/tuneandmanner/wiselydiarybackend/emotion/service/EmotionService.java

#39 감정통계 차트 부분
- 감정통계 차트 조회시 같은 비율일떄 최근 날짜-> emotion_code우선순위로 변경
- Resolves #이슈번호
#39 
어떤 변경 사항이 있나요?
-

#39 감정통계 같은 비율일때 emotion_code우선순위로 변경

---

backend/src/main/java/tuneandmanner/wiselydiarybackend/diary/service/DiaryService.java

#1 일기조회시 날짜별 안내 메세지 변경
메인화면 일기 조회시 날짜 별 안내 메세지 변경
- Resolves #이슈번호
- #1 
어떤 변경 사항이 있나요?
-

#1 일기 조회시 날짜 별 안내 메세지 변경

---

.github/workflows/deploy.yml
backend/src/main/java/tuneandmanner/wiselydiarybackend/WiselyDiaryBackendApplication.java
backend/src/main/java/tuneandmanner/wiselydiarybackend/auth/config/OpenAIClientConfig.java
backend/src/main/java/tuneandmanner/wiselydiarybackend/auth/config/OpenAiConfig.java
backend/src/main/java/tuneandmanner/wiselydiarybackend/common/config/FeignConfig.java
backend/src/main/java/tuneandmanner/wiselydiarybackend/common/config/FileUploadProperties.java
backend/src/main/java/tuneandmanner/wiselydiarybackend/common/config/MultipartConfig.java
backend/src/main/java/tuneandmanner/wiselydiarybackend/stt/client/OpenAIClient.java
backend/src/main/java/tuneandmanner/wiselydiarybackend/stt/controller/WhisperController.java
backend/src/main/java/tuneandmanner/wiselydiarybackend/stt/service/OpenAIClientService.java
build.gradle

- STT 파일 처리 수정: 파일 10MB 넘을 시 압축하여 OpenAI 에 POST 요청 날리기
- Suno 토큰 적용 안되던거 적용되도록 deploy.yml 수정
- Resolves #9 , #25 
어떤 변경 사항이 있나요?
-

fix: STT 파일 처리 로직, Suno 토큰 처리 로직

---

backend/src/main/java/tuneandmanner/wiselydiarybackend/diary/domain/repository/DiaryRepository.java
backend/src/main/java/tuneandmanner/wiselydiarybackend/diary/service/DiaryService.java

- "returned not unique result" 관련 예외 처리
- 비즈니스 로직 상 하루에 일기는 한개만 있어야 하지만, 혹시라도 하루에 여러개의 일기 조회됐을 때 에러 띄우지 말고 그 일기들 중 가장 최근에 작성된 일기 출력하게 함.
- Resolves #127 
어떤 변경 사항이 있나요?
-

fix: DiaryService getDiaryContents 일기 조회 로직 수정

---

.github/workflows/gradle.yml
backend/src/main/java/tuneandmanner/wiselydiarybackend/diary/domain/repository/DiaryRepository.java
backend/src/main/java/tuneandmanner/wiselydiarybackend/diary/service/DiaryService.java

- setup/github-actions -> dev 병합
어떤 변경 사항이 있나요?
-

setup/github-actions -> dev 병합

---

backend/src/main/java/tuneandmanner/wiselydiarybackend/imagesubmit/presentation/ImageController.java
backend/src/main/java/tuneandmanner/wiselydiarybackend/imagesubmit/service/ImageServiceImpl.java

- 첨부 사진 없을 때도 일기 생성되게 수정
- Fixes #48 
어떤 변경 사항이 있나요?
-

fix: 첨부 사진 없을 때도 일기 생성되게 수정

---

backend/src/main/java/tuneandmanner/wiselydiarybackend/imagesubmit/presentation/ImageController.java
backend/src/main/java/tuneandmanner/wiselydiarybackend/imagesubmit/service/ImageServiceImpl.java
backend/src/main/java/tuneandmanner/wiselydiarybackend/stt/service/OpenAIClientService.java

- Resolves #이슈번호
어떤 변경 사항이 있나요?
-

chore: transcription 결과 로깅 추가
